checks:
    php: true

filter:
    paths:
        - src/

    dependency_paths:
        - vendor-patches/

build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
