---
# can be fetched from: https://trello.com/app-key
api_key: beb1cf49bfceca0ea4f7dc063fe54f37

# can be fetched from a board's URL: https://trello.com/b/XXXXX/
board_id: ~

path_part:
    # available variables: %list_name%, %card_name%
    path: '%list_name%/%card_name%'
    priority: 50
    substitutions:
        ' - ': '/'
