---
path_part:
    path: 'YouTube'
    priority: -50

patterns:

    # available variables: see https://github.com/rg3/youtube-dl#output-template
    _: &YOUTUBE_DL_OUTPUT '%(id)s (%(uploader)s, %(upload_date)s)/%(title)s.%(ext)s'

    # available variables: %video_id%, %file_extension%
    folder: '%video_id% (*)' # matches '%(id)s (%(uploader)s, %(upload_date)s)'

    # available variables: %video_id%, %file_extension%
    filename: '*.%file_extension%' # matches '%(title)s.%(ext)s'

    # the keys should match those of "youtube_dl_options"
    extensions:
        audio: mp3
        video: mp4

# Options passed to the 'youtube-dl' python library. Each options set represents one download attempt.
youtube_dl:

    # This should be changed to "YoutubeDl\YoutubeDl" once https://github.com/norkunas/youtube-dl-php/pull/60
    # has been merged.
    class_name: App\YoutubeDl\YoutubeDl

    # Default options for every file type
    _: &DEFAULT_YOUTUBE_DL_OPTION
        continue: true # resume video download when it has failed in the middle of it (using .{ext}.part file)
        add-metadata: true # ensure there's mp3 ID3 tags on the downloaded files
        output: *YOUTUBE_DL_OUTPUT

    options:
        audio:
            -
                <<: *DEFAULT_YOUTUBE_DL_OPTION
                extract-audio: true
                audio-format: mp3
                audio-quality: 0 # best

        video:
            -
                <<: *DEFAULT_YOUTUBE_DL_OPTION
                format: 'mp4[height <=? 720]'
            -
                <<: *DEFAULT_YOUTUBE_DL_OPTION
                format: 'mp4[height <=? 1080p]'
            -
                <<: *DEFAULT_YOUTUBE_DL_OPTION
                format: 'mp4'
