---
playlist_id: ~

# See https://console.developers.google.com/apis/dashboard
# Available variables : %project_root%
auth_config_path: ~

youtube_url_extractor:
    regex: >-
        ~
            https?:\/\/(?:[0-9A-Z-]+\.)?
            (?:
                youtu\.be\/|
                youtube\.com
                (?:
                    \/embed\/|\/v\/|\/watch\?v=|
                    \/ytscreeningroom\?v=|
                    \/feeds\/api\/videos\/|
                    \/user\S*[^\w\-\s]|
                    \S*[^\w\-\s]
                )
            )
            ([\w\-]{11})
            [?=&+%\w-]*
        ~ix
    video_url_index: 0
    video_id_index: 1
